mindmap
  root((Romanticismo e Idealismo))
    Definizione e contesto
      Movimento culturale, letterario, filosofico e artistico
      Europa, prima meta dell'Ottocento
      Opposizione a Illuminismo e Neoclassicismo
      Centralita di intuizione, sentimento, passione, immaginazione, interiorita
    Origini e diffusione
      Sturm und Drang
      Gruppo di Jena (1798-1804)
      Rivista Athenaeum (1797)
      Autori: Novalis, Schlegel, Fichte, Schelling
      Diffusione europea con sviluppi nazionali differenti
    Sei temi del Romanticismo
      Storicismo
        Storia come divenire creativo
        Rivalutazione del Medioevo
      Nazionalismo
        Nazione come identita storico-culturale
      Divinizzazione della natura
        Panteismo naturalistico
      Esaltazione dell'arte
        Armonia tra spirito e natura
      Titanismo o prometeismo
        Lotta per ideali anche con rischio di sconfitta
      Idealismo filosofico
        Ruolo attivo dell'io nella realta conosciuta
    Atteggiamento dell'intellettuale
      Distacco critico dalla realta
      Realta modificabile dall'azione creativa dell'io
    Idealismo filosofico
      Conoscenza da principio interiore infinito
      Coscienza, pensiero, spirito, idee
      Realta visibile come manifestazione dell'invisibile
      Principio con caratteri panteistici
    Superamento del noumeno
      Noumeno: pensabile ma inconoscibile
      Fenomeno: unico terreno certo
      Fenomeno come rappresentazione dell'io pensante
      Conoscenza vera: esperienza piu attivita del soggetto
    Forme dell'idealismo tedesco
      Fichte
        Idealismo soggettivo
        Io puro e Non-Io
      Schelling
        Idealismo oggettivo
        Assoluto come sintesi Io-Natura
      Hegel
        Idealismo assoluto
        Principio: Ragione o Spirito
    Conclusione
      Svolta comune: centralita del soggetto umano
      Realta come processo vivo
      Intreccio tra coscienza, storia, arte e natura
